TITLE: 'repr_table6_3dpw_model'
DEBUG: false
DEBUG_FREQ: 5
LOGDIR: ''
DEVICE: 'cuda'
EXP_NAME: 'table2_3dpw_exp'
OUTPUT_DIR: './data/work_dir' # your path
NUM_WORKERS: 16
SEED_VALUE: 1
DATASET:
  SEQLEN: 16
LOSS:
  KP_2D_W: 100.0
  KP_3D_W: 200.0
  SHAPE_W: 0.06
  POSE_W: 60.0
  D_MOTION_LOSS_W: 0.0
  vel_or_accel_2d_weight: 10.
  vel_or_accel_3d_weight: 100.
  use_accel: False
TRAIN:
  BATCH_SIZE: 64
  NUM_ITERS_PER_EPOCH: 1500
  END_EPOCH: 80
  LR_PATIENCE: 8
  DATA_2D_RATIO: 0.6
  OVERLAP: 0.
  DATASETS_2D:
    - 'Insta'
    # - 'PoseTrack'
  DATASETS_3D:
    - 'MPII3D'
    - 'Human36M'
  DATASET_EVAL: 'ThreeDPW'
  # GEN_LR: 0.0001
  GEN_LR: 0.00001
  GEN_WD: 1.e-5
